/* TRDB Estimator - Complete Working Version with Custom Alerts */

(() => {
  /* ---------------- I18N (EN + AR) ---------------- */
  const I18N = {
    en: {
      dir: 'ltr',
      appTitle: 'TRDB Fit-Out Cost Estimator',
      appSubtitle: 'AI-Powered Office Fit-Out Budgeting (UAE & KSA)',
      projectInputs: 'Project Inputs',
      estimationResults: 'Estimation Results',
      market: 'Market',
      unitsBadge: 'SqFt',
      projectSize: 'Project Size (SqFt)',
      fitOutQuality: 'Fit-Out Quality',
      quality: { Light: 'Light', Standard: 'Standard', Premium: 'Premium' },
      options: 'Options',
      opt: {
        furniture: 'Furniture Supply',
        ffe: 'Loose Furnishings & Décor',
        art: 'Original Art Procurement',
        smart: 'Smart Workplace (IoT/AV)',
        green: 'LEED / Sustainability',
        fast: 'Fast-Track Timeline',
        fullhvac: 'Full HVAC Supply & Plant'
      },
      baseNote: 'Base MEP covers distribution/connection to existing systems. Select "Full HVAC Supply & Plant" to include supply of equipment and plant-side works where required.',
      baseCostLabel: 'TRDB Base (ex-options):',
      totalCostLabel: 'Total Project Cost (with options):',
      whatsIncludedTitle: 'What\'s included in each slice?',
      glossaryTitle: 'Glossary',
      gl: {
        mep: 'Mechanical, Electrical & Plumbing',
        hvac: 'Heating, Ventilation & Air Conditioning',
        bms: 'Building Management System',
        iaq: 'Indoor Air Quality',
        lv: 'Low-Voltage (data/voice/IT/AV cabling & containment)'
      },
      disclaimer: 'Note: Ranges reflect scope, specification and program assumptions. For a firm proposal, use "Email this Estimate", WhatsApp, or book a consultation.',
      stickyCta: 'Book consultation',
      footerNote: 'Estimates are generated by TR Design Build\'s proprietary AI model and are aligned with publicly available industry data in the UAE & KSA.',
      btn: {
        pdf: 'Download PDF',
        email: 'Email this Estimate',
        whatsapp: 'WhatsApp the Estimate',
        consult: 'Book Consultation',
        getEstimate: 'Get Your Estimate'
      },
      scopeLabels: {
        fitout: 'Fit-Out (Base)',
        mep: 'MEP (Base: Mechanical, Electrical & Plumbing)',
        furniture: 'Furniture Supply',
        ffe: 'Loose Furnishings & Décor',
        art: 'Original Art Procurement',
        smart: 'Smart Workplace (IoT/AV)',
        green: 'LEED / Sustainability',
        fast: 'Fast-Track Timeline',
        fullhvac: 'Full HVAC Supply & Plant'
      },
      scope: {
        fitout: [
          'Partitions (gypsum/glass), ceilings, raised floors',
          'Flooring finishes (carpet, vinyl, stone, timber)',
          'Joinery & built-ins (reception, pantry cabinetry)',
          'Wall finishes & painting, decorative elements',
          'Basic lighting fixtures & small power distribution'
        ],
        mep: [
          'Electrical: DBs, wiring, sockets, lighting circuits',
          'Plumbing & drainage for tea points/washrooms (if in scope)',
          'Fire detection & protection: sprinklers, detectors, alarms',
          'Low-voltage (LV) cabling for data/voice/IT/AV rough-in',
          'HVAC distribution to existing systems (ducts, grilles, balancing)'
        ],
        furniture: [
          'Workstations, desks, seating, storage & meeting tables',
          'Soft seating, breakout furniture, delivery & installation'
        ],
        ffe: [
          'Loose furnishings & décor (rugs, lamps), blinds/curtains, acoustic panels',
          'Accessories & small appliances if required'
        ],
        art: [
          'Curated or commissioned unique artworks',
          'Artist/gallery coordination, logistics, certification'
        ],
        smart: [
          'AV (Audio-Visual): VC suites/displays; room booking systems',
          'IoT sensors (occupancy, lighting/AC controls), analytics',
          'Structured cabling upgrades for IT/AV'
        ],
        green: [
          'LEED documentation & commissioning support',
          'Low-VOC materials, certified timber & finishes',
          'HVAC filtration upgrades, water-saving fixtures'
        ],
        fast: [
          'Out-of-hours working (nights/weekends)',
          'Parallel trades resourcing, accelerated procurement',
          'Premium freight & site management uplift'
        ],
        fullhvac: [
          'Supply & install of HVAC equipment and distribution',
          'Valves, insulation, supports, flushing & commissioning',
          'Controls integration and plant-side works (BMS as required)'
        ]
      },
      qualityInfo: {
        Light: {
          title: 'Light Fit-Out',
          summary: 'Cost-efficient finishes with standard MEP to enable quick, functional occupancy.',
          bullets: [
            'Modular partitions and standard ceiling systems',
            'Value-led floor & wall finishes',
            'Standard lighting & small power with basic controls',
            'HVAC duct distribution & balancing to existing systems',
            'Minimal bespoke joinery (reception/pantry as needed)'
          ]
        },
        Standard: {
          title: 'Standard Fit-Out',
          summary: 'Balanced quality and durability with selective feature joinery and sensible MEP upgrades.',
          bullets: [
            'Optimized open-plan layout with select feature walls',
            'Durable mid-tier finishes & acoustic treatments',
            'Layered lighting (task/ambient) with simple controls',
            'HVAC distribution with improved zoning & efficiency',
            'Feature joinery to front-of-house / collaboration areas'
          ]
        },
        Premium: {
          title: 'Premium Fit-Out',
          summary: 'High-end finishes and crafted details with enhanced MEP and smart workplace readiness.',
          bullets: [
            'High-spec finishes with bespoke detailing & materials',
            'Statement joinery & reception features',
            'Advanced lighting scenes & integrated controls',
            'Enhanced HVAC comfort & IAQ measures (distribution)',
            'Seamless AV/IT integration ready for smart workplace'
          ]
        }
      }
    },
    ar: {
      dir: 'rtl',
      appTitle: 'حاسبة تكلفة تجهيز المكاتب TRDB',
      appSubtitle: 'تقدير ميزانية التجهيز الداخلي بالذكاء الاصطناعي (الإمارات والسعودية)',
      projectInputs: 'مدخلات المشروع',
      estimationResults: 'نتائج التقدير',
      market: 'السوق',
      unitsBadge: 'قدم²',
      projectSize: 'مساحة المشروع (قدم²)',
      fitOutQuality: 'جودة التجهيز',
      quality: { Light: 'خفيف', Standard: 'قياسي', Premium: 'فاخر' },
      options: 'الخيارات',
      opt: {
        furniture: 'توريد الأثاث',
        ffe: 'مفروشات وإكسسوارات',
        art: 'اقتناء أعمال فنية أصلية',
        smart: 'مكتب ذكي (إنترنت الأشياء/AV)',
        green: 'الاستدامة/LEED',
        fast: 'برنامج التنفيذ السريع',
        fullhvac: 'توريد وتركيب أنظمة التكييف بالكامل'
      },
      baseNote: 'يغطي نطاق MEP الأساسي التوزيع/الاتصال بالأنظمة القائمة. اختر «توريد وتركيب أنظمة التكييف بالكامل» ليشمل توريد المعدات وأعمال جانب المحطة عند الحاجة.',
      baseCostLabel: 'قيمة TRDB الأساسية (بدون إضافات):',
      totalCostLabel: 'التكلفة الإجمالية (مع الخيارات):',
      whatsIncludedTitle: 'ماذا يتضمّن كل جزء؟',
      glossaryTitle: 'قاموس المصطلحات',
      gl: {
        mep: 'الأعمال الميكانيكية والكهربائية والسباكة',
        hvac: 'التدفئة والتهوية وتكييف الهواء',
        bms: 'نظام إدارة المباني',
        iaq: 'جودة الهواء الداخلي',
        lv: 'الجهد المنخفض (بيانات/صوت/تقنيات IT/AV)'
      },
      disclaimer: 'ملاحظة: تعكس القيم نطاق الأعمال والمواصفات والبرنامج. للحصول على عرض ملزم، استخدم خيار البريد الإلكتروني أو واتساب أو احجز استشارة.',
      stickyCta: 'احجز استشارة',
      footerNote: 'يتم إنشاء التقديرات بواسطة نموذج ذكاء اصطناعي خاص بشركة TR Design Build ومتوافق مع بيانات الصناعة المتاحة علنًا في الإمارات والسعودية.',
      btn: {
        pdf: 'تحميل PDF',
        email: 'أرسل التقدير عبر البريد الإلكتروني',
        whatsapp: 'أرسل التقدير عبر واتساب',
        consult: 'احجز استشارة',
        getEstimate: 'احصل على تقديرك'
      },
      scopeLabels: {
        fitout: 'أعمال التجهيز (أساسي)',
        mep: 'الأعمال الكهروميكانيكية (MEP)',
        furniture: 'توريد الأثاث',
        ffe: 'مفروشات وإكسسوارات',
        art: 'اقتناء أعمال فنية أصلية',
        smart: 'مكتب ذكي (إنترنت الأشياء/AV)',
        green: 'الاستدامة/LEED',
        fast: 'برنامج التنفيذ السريع',
        fullhvac: 'توريد وتركيب أنظمة التكييف بالكامل'
      },
      scope: {
        fitout: [
          'القواطع (جبس/زجاج)، الأسقف، الأرضيات المرتفعة',
          'تشطيبات الأرضيات (سجاد، فينيل، حجر، خشب)',
          'نجارة وعناصر مدمجة (الاستقبال، خزائن البانتري)',
          'تشطيبات الجدران والدهانات، عناصر ديكور',
          'إنارة أساسية وتوزيع قدرة كهربائية خفيفة'
        ],
        mep: [
          'الكهرباء: لوحات توزيع، تمديدات وأسلاك، مخارج وإنارة',
          'السباكة والصرف لنقاط المياه/دورات المياه (عند إدراجها في النطاق)',
          'أنظمة الكشف والإطفاء: رشاشات، كواشف، أجهزة إنذار',
          'تمديدات الجهد المنخفض للبيانات/الصوت/تقنيات IT/AV',
          'توزيع التكييف على الأنظمة القائمة (مجاري هواء، فتحات، موازنة)'
        ],
        furniture: [
          'محطات عمل، مكاتب، كراسي، خزائن، وطاولات اجتماعات',
          'جلسات مريحة ومناطق استراحة، وتوصيل وتركيب'
        ],
        ffe: [
          'مفروشات وإكسسوارات (سجاد، مصابيح)، ستائر/بلّاكات، ألواح صوتية',
          'إكسسوارات وأجهزة صغيرة عند الحاجة'
        ],
        art: ['أعمال فنية منسّقة أو مكلّفة خصيصًا', 'تنسيق مع الفنان/المعرض، لوجستيات وشهادات'],
        smart: [
          'أنظمة AV: شاشات ومؤتمرات مرئية؛ حجز الغرف',
          'حساسات إنترنت الأشياء؛ تحكم الإضاءة/التكييف؛ تحليلات',
          'ترقيات الكوابل المنظمة لـ IT/AV'
        ],
        green: [
          'توثيق LEED ودعم التشغيل والتسليم',
          'مواد منخفضة الانبعاثات؛ أخشاب وتشطيبات معتمدة',
          'ترقيات ترشيح الهواء للتكييف؛ تجهيزات موفرة للمياه'
        ],
        fast: ['أعمال خارج الدوام (ليلاً/عطلات)', 'توازي الأعمال وتسريع المشتريات', 'شحن مميز ورفع إدارة الموقع'],
        fullhvac: [
          'توريد وتركيب معدات وأنظمة التكييف وتوزيعها',
          'صمامات، عوازل، دعامات، غسيل وتشغيل واختبارات',
          'تكامل أنظمة التحكم وأعمال جانب المحطة (BMS عند الحاجة)'
        ]
      },
      qualityInfo: {
        Light: {
          title: 'تجهيز خفيف',
          summary: 'تشطيبات اقتصادية مع أعمال MEP قياسية لتمكين إشغال سريع وعملي.',
          bullets: [
            'قواطع وأنظمة أسقف قياسية',
            'تشطيبات أرضيات وجدران ذات قيمة',
            'إنارة قياسية وقدرة كهربائية خفيفة بتحكم بسيط',
            'توزيع مجاري الهواء وموازنة على الأنظمة القائمة',
            'أعمال نجارة مخصصة محدودة (الاستقبال/البانتري)'
          ]
        },
        Standard: {
          title: 'تجهيز قياسي',
          summary: 'توازن بين الجودة والمتانة مع نجارة مميزة انتقائية وترقيات منطقية لـ MEP.',
          bullets: [
            'مخطط مفتوح محسّن مع جدران مميزة مختارة',
            'تشطيبات متوسطة المتانة ومعالجات صوتية',
            'طبقات إنارة (وظيفية/عامة) مع تحكم بسيط',
            'توزيع تكييف بتحسين مناطق وكفاءة',
            'نجارة واجهة أمامية ومناطق تعاونية'
          ]
        },
        Premium: {
          title: 'تجهيز فاخر',
          summary: 'تشطيبات عالية المواصفات وتفاصيل مصنّعة مع MEP معزّز واستعداد مكتب ذكي.',
          bullets: [
            'تشطيبات عالية المواصفات وتفاصيل مخصصة',
            'نجارة مميزة وواجهة استقبال',
            'مشاهد إنارة متقدمة وتكامل تحكم',
            'راحة وجودة هواء داخلي معزّزة (توزيع)',
            'تكامل سلس لـ AV/IT استعدادًا للمكتب الذكي'
          ]
        }
      }
    }
  };

  /* ---------------- DOM refs ---------------- */
  const els = {
    langEN: document.getElementById('lang-en'),
    langAR: document.getElementById('lang-ar'),
    appTitle: document.getElementById('t_appTitle'),
    appSubtitle: document.getElementById('t_appSubtitle'),
    hInputs: document.getElementById('t_projectInputs'),
    market: document.getElementById('market'),
    unitsBadge: document.getElementById('t_unitsBadge'),
    projectSize: document.getElementById('t_projectSize'),
    sqft: document.getElementById('sqft'),
    sqftOut: document.getElementById('sqftOut'),
    sqftInput: document.getElementById('sqftInput'),
    btnMinus: document.getElementById('btnMinus'),
    btnPlus: document.getElementById('btnPlus'),
    chips: Array.from(document.querySelectorAll('.chip[data-size]')),
    qualityHdr: document.getElementById('t_fitOutQuality'),
    quality: [...document.querySelectorAll('input[name="quality"]')],
    qLight: document.getElementById('t_qualityLight'),
    qStandard: document.getElementById('t_qualityStandard'),
    qPremium: document.getElementById('t_qualityPremium'),
    qualityDesc: document.getElementById('qualityDesc'),
    optionsHdr: document.getElementById('t_options'),
    opt: {
      furniture: document.getElementById('opt-furniture'),
      ffe: document.getElementById('opt-ffe'),
      art: document.getElementById('opt-art'),
      smart: document.getElementById('opt-smart'),
      green: document.getElementById('opt-green'),
      fast: document.getElementById('opt-fast'),
      fullhvac: document.getElementById('opt-fullhvac')
    },
    optTxt: {
      furniture: document.getElementById('t_optionFurniture'),
      ffe: document.getElementById('t_optionLooseDecor'),
      art: document.getElementById('t_optionArt'),
      smart: document.getElementById('t_optionSmartWorkplace'),
      green: document.getElementById('t_optionGreen'),
      fast: document.getElementById('t_optionFastTrack'),
      fullhvac: document.getElementById('t_optionHVACFull')
    },
    baseNote: document.getElementById('t_baseNote'),
    hResults: document.getElementById('t_estimationResults'),
    baseLabel: document.getElementById('t_baseCostLabel'),
    totalLabel: document.getElementById('t_totalCostLabel'),
    trdbBase: document.getElementById('trdbBase'),
    total: document.getElementById('total'),
    canvas: document.getElementById('pie'),
    incTitle: document.getElementById('t_whatsIncludedTitle'),
    infoPanel: document.getElementById('info-panel'),
    glossaryTitle: document.getElementById('t_glossaryTitle'),
    gl_mep: document.getElementById('t_gl_mep'),
    gl_hvac: document.getElementById('t_gl_hvac'),
    gl_bms: document.getElementById('t_gl_bms'),
    gl_iaq: document.getElementById('t_gl_iaq'),
    gl_lv: document.getElementById('t_gl_lv'),
    disclaimer: document.getElementById('t_disclaimer'),
    yr: document.getElementById('yr'),
    stickyCta: document.getElementById('t_stickyCta'),
    footerNote: document.getElementById('t_footerNote'),
    btnConsult: document.getElementById('btn-consult')
  };
  
  if (els.yr) els.yr.textContent = new Date().getFullYear();

  /* ---------------- CONFIG ---------------- */
  const CONFIG = {
    UAE_Dubai: {
      ccy: 'AED',
      bands: { Light: [187, 272], Standard: [255, 357], Premium: [357, 510] },
      split: { fitout: 0.52, mep: 0.18 },
      options: { furniture: 0.1, ffe: 0.09, art: 0.02, smart: 0.06, green: 0.05, fast: 0.08, fullhvac: 0.18 }
    },
    UAE_AbuDhabi: {
      ccy: 'AED',
      bands: { Light: [178, 264], Standard: [246, 340], Premium: [348, 493] },
      split: { fitout: 0.52, mep: 0.18 },
      options: { furniture: 0.1, ffe: 0.09, art: 0.02, smart: 0.06, green: 0.05, fast: 0.08, fullhvac: 0.18 }
    },
    UAE_RAK: {
      ccy: 'AED',
      bands: { Light: [162, 238], Standard: [221, 306], Premium: [314, 442] },
      split: { fitout: 0.52, mep: 0.18 },
      options: { furniture: 0.1, ffe: 0.09, art: 0.02, smart: 0.06, green: 0.05, fast: 0.08, fullhvac: 0.18 }
    },
    KSA_Riyadh: {
      ccy: 'SAR',
      bands: { Light: [196, 280], Standard: [272, 374], Premium: [374, 527] },
      split: { fitout: 0.52, mep: 0.18 },
      options: { furniture: 0.11, ffe: 0.1, art: 0.02, smart: 0.06, green: 0.05, fast: 0.09, fullhvac: 0.17 }
    },
    KSA_Jeddah: {
      ccy: 'SAR',
      bands: { Light: [187, 272], Standard: [264, 366], Premium: [366, 510] },
      split: { fitout: 0.52, mep: 0.18 },
      options: { furniture: 0.11, ffe: 0.1, art: 0.02, smart: 0.06, green: 0.05, fast: 0.09, fullhvac: 0.17 }
    }
  };

  const COLORS = {
    fitout: '#1b4a68',
    mep: '#2c6e93',
    options: ['#f08c2b', '#edc24a', '#a3d9a5', '#6cc4ff', '#4fbf9f', '#c18cff', '#ff9db0']
  };

  /* ---------------- State & helpers ---------------- */
  const SQFT_PER_SQM = 10.7639104167097;
  const sqmFromSqft = (sf) => sf / SQFT_PER_SQM;
  const sqftFromSqm = (sm) => sm * SQFT_PER_SQM;

  const state = {
    lang: localStorage.getItem('trdb-lang') || 'en',
    units: localStorage.getItem('trdb-units') || 'sqft'
  };

  const fmt = (ccy, n) =>
    new Intl.NumberFormat('en', {
      style: 'currency',
      currency: ccy === 'AED' ? 'AED' : 'SAR',
      maximumFractionDigits: 0
    }).format(n);

  const getMarketCfg = () => CONFIG[els.market.value];
  const getQuality = () => els.quality.find((r) => r.checked)?.value || 'Standard';
  const getSqft = () => +els.sqft.value;

  function setDir(dir) {
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', state.lang);
  }

  const unitLabel = () =>
    state.units === 'sqm' ? (state.lang === 'ar' ? 'م²' : 'm²') : (state.lang === 'ar' ? 'قدم²' : 'SqFt');

  const baseSizeLabel = () => (state.lang === 'ar' ? 'مساحة المشروع' : 'Project Size');

  /* ---------------- i18n apply ---------------- */
  function applyI18n() {
    const t = I18N[state.lang];
    setDir(t.dir);

    els.appTitle.textContent = t.appTitle;
    els.appSubtitle.textContent = t.appSubtitle;
    els.hInputs.textContent = t.projectInputs;
    els.hResults.textContent = t.estimationResults;

    els.unitsBadge.textContent = unitLabel();
    els.projectSize.textContent = baseSizeLabel() + ' (' + unitLabel() + ')';

    els.qualityHdr.textContent = t.fitOutQuality;
    els.qLight.textContent = t.quality.Light;
    els.qStandard.textContent = t.quality.Standard;
    els.qPremium.textContent = t.quality.Premium;

    document.getElementById('t_options').textContent = t.options;
    els.optTxt.furniture.textContent = t.opt.furniture;
    els.optTxt.ffe.textContent = t.opt.ffe;
    els.optTxt.art.textContent = t.opt.art;
    els.optTxt.smart.textContent = t.opt.smart;
    els.optTxt.green.textContent = t.opt.green;
    els.optTxt.fast.textContent = t.opt.fast;
    els.optTxt.fullhvac.textContent = t.opt.fullhvac;

    els.baseNote.textContent = t.baseNote;
    els.baseLabel.textContent = t.baseCostLabel;
    els.totalLabel.textContent = t.totalCostLabel;

    els.incTitle.textContent = t.whatsIncludedTitle;
    els.glossaryTitle.textContent = t.glossaryTitle;
    els.gl_mep.textContent = t.gl.mep;
    els.gl_hvac.textContent = t.gl.hvac;
    els.gl_bms.textContent = t.gl.bms;
    els.gl_iaq.textContent = t.gl.iaq;
    els.gl_lv.textContent = t.gl.lv;
    els.disclaimer.textContent = t.disclaimer;

    els.stickyCta.textContent = t.stickyCta;
    els.footerNote.textContent = t.footerNote;

    els.btnConsult.querySelector('span').textContent = t.btn.consult;

    Array.from(els.market.options).forEach((opt) => {
      opt.textContent =
        state.lang === 'ar'
          ? opt.getAttribute('data-ar') || opt.textContent
          : opt.getAttribute('data-en') || opt.textContent;
    });

    document.getElementById('t_market').textContent = t.market;

    renderInfoPanel({
      furniture: els.opt.furniture?.checked,
      ffe: els.opt.ffe?.checked,
      art: els.opt.art?.checked,
      smart: els.opt.smart?.checked,
      green: els.opt.green?.checked,
      fast: els.opt.fast?.checked,
      fullhvac: els.opt.fullhvac?.checked
    });

    updateUnitToggleUI();
    reflectDisplaySize();
  }

  /* ---------------- Quality card ---------------- */
  function renderQualityDesc(selectedQuality) {
    const t = I18N[state.lang];
    const box = els.qualityDesc;
    if (!box) return;
    const info = t.qualityInfo[selectedQuality] || t.qualityInfo['Standard'];
    const bullets = (info.bullets || [])
      .map(
        (b) => '<div class="q-item"><span class="q-dot"></span><span>' + b + '</span></div>'
      )
      .join('');
    box.innerHTML = 
      '<div class="q-title">' +
        '<span class="q-badge">' + (t.quality[selectedQuality] || selectedQuality) + '</span>' +
        '<span>' + info.title + '</span>' +
      '</div>' +
      '<p>' + info.summary + '</p>' +
      '<div class="q-grid">' + bullets + '</div>';
    box.classList.add('show');
  }

  /* ---------------- Estimator core ---------------- */
  const calcTRDB = (cfg, quality, sqft, selected) => {
    const bands = cfg.bands[quality];
    const rate = (bands[0] + bands[1]) / 2;
    const base = rate * sqft;
    const fitoutVal = base * cfg.split.fitout;
    const mepVal = base * cfg.split.mep;

    const defs = [
      { key: 'furniture', label: 'furniture', pct: cfg.options.furniture },
      { key: 'ffe', label: 'ffe', pct: cfg.options.ffe },
      { key: 'art', label: 'art', pct: cfg.options.art },
      { key: 'smart', label: 'smart', pct: cfg.options.smart },
      { key: 'green', label: 'green', pct: cfg.options.green },
      { key: 'fast', label: 'fast', pct: cfg.options.fast },
      { key: 'fullhvac', label: 'fullhvac', pct: cfg.options.fullhvac }
    ];

    const breakdown = defs
      .map((d, i) => (selected[d.key] ? { key: d.key, label: d.label, value: base * d.pct, color: COLORS.options[i] } : null))
      .filter(Boolean);

    const optionsTotal = breakdown.reduce((a, b) => a + b.value, 0);
    const total = base + optionsTotal;
    return { rate: rate, base: base, fitoutVal: fitoutVal, mepVal: mepVal, breakdown: breakdown, total: total };
  };

  /* ---------------- Chart ---------------- */
  let chart;
  const renderChart = (ccy, fitoutVal, mepVal, breakdown) => {
    const t = I18N[state.lang];
    const labels = [t.scopeLabels.fitout, t.scopeLabels.mep].concat(breakdown.map((d) => t.scopeLabels[d.label]));
    const data = [fitoutVal, mepVal].concat(breakdown.map((d) => d.value));
    const colors = [COLORS.fitout, COLORS.mep].concat(breakdown.map((d) => d.color));

    if (chart) chart.destroy();
    chart = new Chart(els.canvas, {
      type: 'doughnut',
      data: { labels: labels, datasets: [{ data: data, backgroundColor: colors, hoverOffset: 6 }] },
      options: {
        responsive: true,
        plugins: {
          legend: { position: 'bottom' },
          tooltip: {
            callbacks: {
              label: function(ctx) {
                const val = ctx.parsed || 0;
                const tot = ctx.dataset.data.reduce((a, b) => a + b, 0) || 1;
                const pct = Math.round((val / tot) * 100);
                return ctx.label + ': ' + fmt(ccy, val) + ' (' + pct + '%)';
              }
            }
          }
        },
        cutout: '58%'
      }
    });
  };

  /* ---------------- Info panel ---------------- */
  function renderInfoPanel(selected) {
    const t = I18N[state.lang];
    const el = els.infoPanel;
    if (!el) return;

    const cats = [
      { key: 'fitout', label: t.scopeLabels.fitout, force: true },
      { key: 'mep', label: t.scopeLabels.mep, force: true },
      { key: 'furniture', label: t.scopeLabels.furniture, selected: selected.furniture },
      { key: 'ffe', label: t.scopeLabels.ffe, selected: selected.ffe },
      { key: 'art', label: t.scopeLabels.art, selected: selected.art },
      { key: 'smart', label: t.scopeLabels.smart, selected: selected.smart },
      { key: 'green', label: t.scopeLabels.green, selected: selected.green },
      { key: 'fast', label: t.scopeLabels.fast, selected: selected.fast },
      { key: 'fullhvac', label: t.scopeLabels.fullhvac, selected: selected.fullhvac }
    ];

    const html = cats
      .filter((c) => c.force || c.selected)
      .map((c) => {
        const scopeItems = I18N[state.lang].scope[c.key] || [];
        const items = scopeItems.map((s) => '<li>' + s + '</li>').join('');
        const tick = c.selected ? '<span class="info-chip">✓</span>' : '';
        return '<div class="info-cat">' + c.label + tick + '</div><ul class="info-list">' + items + '</ul>';
      })
      .join('');

    el.innerHTML = html || '<div class="small">' + (state.lang === 'ar' ? 'اختر الخيارات لعرض التفاصيل.' : 'Select options to see details.') + '</div>';
  }

  /* ---------------- Chip highlight ---------------- */
  function markActiveChips(sizeValSqft) {
    if (!els.chips || els.chips.length === 0) return;
    let matched = null;
    els.chips.forEach((ch) => {
      ch.classList.remove('active');
      ch.setAttribute('aria-pressed', 'false');
      const ds = parseInt(ch.dataset.size, 10);
      if (isFinite(ds) && ds === sizeValSqft) matched = ch;
    });
    if (matched) {
      matched.classList.add('active');
      matched.setAttribute('aria-pressed', 'true');
    }
  }

  /* ---------------- UPDATE pipeline ---------------- */
  const update = () => {
    const cfg = getMarketCfg();
    const quality = getQuality();
    const sqft = getSqft();

    reflectDisplaySize();
    renderQualityDesc(quality);

    const trdb = calcTRDB(cfg, quality, sqft, {
      furniture: els.opt.furniture?.checked,
      ffe: els.opt.ffe?.checked,
      art: els.opt.art?.checked,
      smart: els.opt.smart?.checked,
      green: els.opt.green?.checked,
      fast: els.opt.fast?.checked,
      fullhvac: els.opt.fullhvac?.checked
    });

    const areaInDisplayUnits = state.units === 'sqm' ? sqmFromSqft(Math.max(1, sqft)) : Math.max(1, sqft);
    const perUnit = trdb.base / areaInDisplayUnits;
    const unitSuffix = unitLabel();

    els.trdbBase.textContent = fmt(cfg.ccy, trdb.base) + '  |  ' + perUnit.toFixed(0) + ' ' + cfg.ccy + '/' + unitSuffix;
    els.total.textContent = fmt(cfg.ccy, trdb.total);

    renderChart(cfg.ccy, trdb.fitoutVal, trdb.mepVal, trdb.breakdown);
    renderInfoPanel({
      furniture: els.opt.furniture?.checked,
      ffe: els.opt.ffe?.checked,
      art: els.opt.art?.checked,
      smart: els.opt.smart?.checked,
      green: els.opt.green?.checked,
      fast: els.opt.fast?.checked,
      fullhvac: els.opt.fullhvac?.checked
    });

    markActiveChips(getSqft());
  };

  /* ---------------- PDF helpers ---------------- */
  async function loadLogoAsDataURL() {
    const paths = ['/public/assets/trdb-logo.png', '/assets/trdb-logo.png', '/public/assets/logo.png'];
    for (const p of paths) {
      try {
        const dataURL = await new Promise((resolve, reject) => {
          const img = new Image();
          img.crossOrigin = 'anonymous';
          img.onload = () => {
            const c = document.createElement('canvas');
            c.width = img.naturalWidth;
            c.height = img.naturalHeight;
            const ctx = c.getContext('2d');
            ctx.drawImage(img, 0, 0);
            resolve(c.toDataURL('image/png'));
          };
          img.onerror = reject;
          img.src = p + '?v=' + Date.now();
        });
        return dataURL;
      } catch (e) {
        console.log('Failed to load logo from:', p);
      }
    }
    return null;
  }

  function makeFooterImage(options) {
    const lang = options.lang || 'en';
    const width = options.width || 595;
    const height = options.height || 48;
    
    const c = document.createElement('canvas');
    c.width = width;
    c.height = height;
    const ctx = c.getContext('2d');

    ctx.fillStyle = '#e6eaee';
    ctx.fillRect(0, 0, width, 1);

    const year = new Date().getFullYear();
    const textEN1 = '© ' + year + ' TR Design Build – TRDB. All rights reserved.';
    const textEN2 = 'Estimates are generated by TR Design Build\'s proprietary AI model and are aligned with publicly available industry data in the UAE & KSA.';
    const textAR1 = '© ' + year + ' شركة TR Design Build – TRDB. جميع الحقوق محفوظة.';
    const textAR2 = 'يتم إنشاء التقديرات بواسطة نموذج ذكاء اصطناعي خاص بشركة TR Design Build ومتوافق مع بيانات الصناعة المتاحة علنًا في الإمارات والسعودية.';

    ctx.font = '12px system-ui, Arial';
    ctx.fillStyle = '#5e738a';
    ctx.textBaseline = 'top';
    const padX = 18;
    const padY = 8;

    if (lang === 'ar') {
      ctx.direction = 'rtl';
      ctx.textAlign = 'right';
      ctx.fillText(textAR1, width - padX, padY);
      ctx.font = '11px system-ui, Arial';
      ctx.fillText(textAR2, width - padX, padY + 16);
    } else {
      ctx.direction = 'ltr';
      ctx.textAlign = 'left';
      ctx.fillText(textEN1, padX, padY);
      ctx.font = '11px system-ui, Arial';
      ctx.fillText(textEN2, padX, padY + 16);
    }

    return c.toDataURL('image/png');
  }

  /* ---------------- PDF export ---------------- */
  const downloadPDF = async () => {
    if (!window.jspdf) {
      showCustomAlert('PDF library not loaded. Please refresh the page.');
      return;
    }
    
    const jsPDF = window.jspdf.jsPDF;
    const mainNode = document.querySelector('main');
    if (!mainNode) return;

    const detailBlocks = Array.from(document.querySelectorAll('details.info'));
    const prevOpen = detailBlocks.map((d) => d.open);
    detailBlocks.forEach((d) => (d.open = true));

    const isArabic = (document.documentElement.getAttribute('lang') || '').toLowerCase().startsWith('ar');
    const lang = isArabic ? 'ar' : 'en';

    try {
      const canvas = await html2canvas(mainNode, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff'
      });

      const pdf = new jsPDF('p', 'pt', 'a4');
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const margin = 18;
      const footerH = 48;
      const logoData = await loadLogoAsDataURL();
      const headerH = 46;
      const footerImg = makeFooterImage({ lang: lang, width: 595, height: footerH });

      function drawHeaderFooter(pageIndex) {
        pdf.addImage(footerImg, 'PNG', 0, pageH - footerH, pageW, footerH, undefined, 'FAST');
        if (pageIndex === 0 && logoData) {
          pdf.addImage(logoData, 'PNG', margin, margin - 2, 90, 28, undefined, 'FAST');
        }
      }

      const imgW = pageW - margin * 2;
      const imgH = (canvas.height * imgW) / canvas.width;
      const usableH = pageH - margin - footerH - headerH;

      let sy = 0;
      let pageIndex = 0;
      
      while (sy < canvas.height) {
        const sliceH = Math.min(usableH * (canvas.width / imgW), canvas.height - sy);
        const pageCanvas = document.createElement('canvas');
        pageCanvas.width = canvas.width;
        pageCanvas.height = sliceH;
        const pctx = pageCanvas.getContext('2d');
        pctx.drawImage(canvas, 0, sy, canvas.width, sliceH, 0, 0, canvas.width, sliceH);
        const pageImg = pageCanvas.toDataURL('image/jpeg', 0.95);

        if (pageIndex > 0) pdf.addPage();
        drawHeaderFooter(pageIndex);
        
        const yStart = pageIndex === 0 ? margin + headerH : margin;
        const drawH = sliceH * (imgW / canvas.width);
        pdf.addImage(pageImg, 'JPEG', margin, yStart, imgW, drawH, undefined, 'FAST');

        sy += sliceH;
        pageIndex++;
      }

      const filename = 'TRDB_Estimate_' + new Date().toISOString().slice(0, 10) + '.pdf';
      pdf.save(filename);
    } catch (err) {
      console.error('PDF export failed:', err);
      showCustomAlert('PDF export failed. Please try again.');
    } finally {
      detailBlocks.forEach((d, i) => (d.open = prevOpen[i]));
    }
  };

  /* ---------------- Email/WhatsApp ---------------- */
  const buildSnapshotText = (total, sqft, quality) => {
    const t = I18N[state.lang];
    const sizeValue = state.units === 'sqm' ? Math.round(sqmFromSqft(sqft)) : sqft;
    const lines = [
      t.totalCostLabel + ' ' + els.total.textContent,
      baseSizeLabel() + ': ' + sizeValue.toLocaleString() + ' ' + unitLabel(),
      t.fitOutQuality + ': ' + (t.quality[quality] || quality),
      '',
      t.options + ':',
      '• ' + t.opt.furniture + ': ' + (els.opt.furniture.checked ? '✓' : '–'),
      '• ' + t.opt.ffe + ': ' + (els.opt.ffe.checked ? '✓' : '–'),
      '• ' + t.opt.art + ': ' + (els.opt.art.checked ? '✓' : '–'),
      '• ' + t.opt.smart + ': ' + (els.opt.smart.checked ? '✓' : '–'),
      '• ' + t.opt.green + ': ' + (els.opt.green.checked ? '✓' : '–'),
      '• ' + t.opt.fast + ': ' + (els.opt.fast.checked ? '✓' : '–'),
      '• ' + t.opt.fullhvac + ': ' + (els.opt.fullhvac.checked ? '✓' : '–')
    ];
    return lines.join('\n');
  };

  const emailEstimate = () => {
    const t = I18N[state.lang];
    const marketText = Array.from(els.market.options)[els.market.selectedIndex].textContent;
    const subject = encodeURIComponent(t.appTitle + ' – ' + marketText);
    const body = encodeURIComponent(buildSnapshotText(els.total.textContent, getSqft(), getQuality()));
    window.location.href = 'mailto:?subject=' + subject + '&body=' + body;
  };

  const whatsappEstimate = () => {
    const t = I18N[state.lang];
    const marketText = Array.from(els.market.options)[els.market.selectedIndex].textContent;
    const head = t.appTitle + '\n' + t.market + ': ' + marketText;
    const body = buildSnapshotText(els.total.textContent, getSqft(), getQuality());
    const msg = encodeURIComponent(head + '\n\n' + body);
    const url = 'https://wa.me/?text=' + msg;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  /* ---------------- Size display ---------------- */
  function reflectDisplaySize() {
    const sqft = getSqft();
    const displayVal = state.units === 'sqm' ? Math.round(sqmFromSqft(sqft)) : sqft;
    els.sqftOut.textContent = displayVal.toLocaleString();
    if (els.sqftInput) els.sqftInput.value = displayVal.toLocaleString();
  }

  /* ---------------- Unit toggle ---------------- */
  let unitToggleRoot = null;
  function ensureUnitToggle() {
    if (unitToggleRoot) return;
    const sizeRow = els.projectSize?.closest('.row') || document.querySelector('.inputs .row');
    if (!sizeRow) return;
    unitToggleRoot = sizeRow.querySelector('.unit-toggle');
    if (!unitToggleRoot) {
      unitToggleRoot = document.createElement('div');
      unitToggleRoot.className = 'chips unit-toggle';
      unitToggleRoot.style.marginTop = '6px';
      unitToggleRoot.innerHTML = '<button type="button" class="chip" data-unit="sqft">SqFt</button><button type="button" class="chip" data-unit="sqm">m²</button>';
      const chipsBlock = sizeRow.querySelector('.chips');
      if (chipsBlock && chipsBlock.nextSibling) {
        chipsBlock.parentNode.insertBefore(unitToggleRoot, chipsBlock.nextSibling);
      } else {
        sizeRow.appendChild(unitToggleRoot);
      }
    }
    unitToggleRoot.addEventListener('click', (e) => {
      const btn = e.target.closest('[data-unit]');
      if (!btn) return;
      const nextUnits = btn.getAttribute('data-unit');
      if (nextUnits !== 'sqft' && nextUnits !== 'sqm') return;
      if (nextUnits === state.units) return;

      state.units = nextUnits;
      localStorage.setItem('trdb-units', state.units);
      updateUnitToggleUI();

      els.unitsBadge.textContent = unitLabel();
      els.projectSize.textContent = baseSizeLabel() + ' (' + unitLabel() + ')';
      reflectDisplaySize();
      update();
    });
  }

  function updateUnitToggleUI() {
    ensureUnitToggle();
    if (!unitToggleRoot) return;
    const btns = Array.from(unitToggleRoot.querySelectorAll('[data-unit]'));
    btns.forEach((b) => {
      b.classList.remove('active');
      const u = b.getAttribute('data-unit');
      b.textContent = u === 'sqm' ? (state.lang === 'ar' ? 'م²' : 'm²') : (state.lang === 'ar' ? 'قدم²' : 'SqFt');
      if (u === state.units) b.classList.add('active');
    });
  }

  /* ---------------- Events ---------------- */
  function clamp(n, min, max) {
    return Math.max(min, Math.min(max, n));
  }
  function cleanNumber(v) {
    return String(v).replace(/[^\d]/g, '');
  }
  function setFill() {
    const min = parseFloat(els.sqft.min);
    const max = parseFloat(els.sqft.max);
    const val = parseFloat(els.sqft.value);
    const pct = ((val - min) / (max - min)) * 100;
    els.sqft.style.setProperty('--fill', pct + '%');
  }
  function setSqft(valueSqft) {
    const n = clamp(parseInt(cleanNumber(valueSqft || els.sqft.value), 10) || 0, parseFloat(els.sqft.min), parseFloat(els.sqft.max));
    els.sqft.value = n;
    reflectDisplaySize();
    setFill();
    markActiveChips(n);
    update();
  }

  ['input', 'change'].forEach((e) => {
    els.market.addEventListener(e, (evt) => {
      const marketLabel = evt.target.options[evt.target.selectedIndex].text;
      if (typeof gtag === 'function') {
        gtag('event', 'market_selected', {
          'market': marketLabel,
          'market_value': evt.target.value
        });
      }
      update();
    });
    
    els.sqft.addEventListener(e, update);
    els.quality.forEach((r) => r.addEventListener(e, update));
    Object.values(els.opt).forEach((chk) => {
      if (chk) chk.addEventListener(e, update);
    });
  });

  if (els.sqft) {
    els.sqft.addEventListener('input', (e) => setSqft(e.target.value));
  }
  if (els.sqftInput) {
    els.sqftInput.addEventListener('input', (e) => {
      const raw = parseInt(cleanNumber(e.target.value), 10) || 0;
      const sf = state.units === 'sqm' ? Math.round(sqftFromSqm(raw)) : raw;
      setSqft(sf);
    });
  }
  if (els.btnMinus) els.btnMinus.addEventListener('click', () => setSqft(parseFloat(cleanNumber(els.sqft.value)) - 500));
  if (els.btnPlus) els.btnPlus.addEventListener('click', () => setSqft(parseFloat(cleanNumber(els.sqft.value)) + 500));

  els.chips.forEach((ch) => ch.addEventListener('click', () => setSqft(ch.dataset.size)));

  /* ---------------- Custom Alert Dialog ---------------- */
  function showCustomAlert(message) {
    const alertOverlay = document.createElement('div');
    alertOverlay.style.cssText = 'position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0, 0, 0, 0.5); display: flex; align-items: center; justify-content: center; z-index: 10000;';
    
    const alertBox = document.createElement('div');
    alertBox.style.cssText = 'background: white; border-radius: 16px; padding: 24px; max-width: 400px; width: 90%; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2); text-align: center;';
    
    const header = document.createElement('h3');
    header.textContent = 'TRDB Cost Estimator Says';
    header.style.cssText = 'margin: 0 0 16px 0; color: #132636; font-size: 1.1rem; font-weight: 700;';
    
    const messageDiv = document.createElement('p');
    messageDiv.textContent = message;
    messageDiv.style.cssText = 'margin: 0 0 20px 0; color: #0b1b26; line-height: 1.5;';
    
    const closeBtn = document.createElement('button');
    closeBtn.textContent = 'Close';
    closeBtn.className = 'btn cta';
    closeBtn.style.cssText = 'width: 100%; padding: 12px; border: none; border-radius: 12px; background: #f08c2b; color: white; font-weight: 700; cursor: pointer; font-size: 1rem;';
    closeBtn.onclick = () => document.body.removeChild(alertOverlay);
    
    alertBox.appendChild(header);
    alertBox.appendChild(messageDiv);
    alertBox.appendChild(closeBtn);
    alertOverlay.appendChild(alertBox);
    
    document.body.appendChild(alertOverlay);
    
    alertOverlay.addEventListener('click', (e) => {
      if (e.target === alertOverlay) {
        document.body.removeChild(alertOverlay);
      }
    });
  }

  /* ---------------- Lead Capture Modal ---------------- */
  function openLeadModal() {
    const modal = document.getElementById('leadModal');
    const summary = document.getElementById('leadEstimateSummary');
    
    const market = Array.from(els.market.options)[els.market.selectedIndex].text;
    const sizeValue = state.units === 'sqm' ? Math.round(sqmFromSqft(getSqft())) : getSqft();
    const quality = getQuality();
    const total = els.total.textContent;
    
    summary.innerHTML = '<strong>Market:</strong> ' + market + '<br>' +
      '<strong>Size:</strong> ' + sizeValue.toLocaleString() + ' ' + unitLabel() + '<br>' +
      '<strong>Quality:</strong> ' + quality + '<br>' +
      '<strong>Total Cost:</strong> ' + total;
    
    modal.style.display = 'flex';
    
    if (typeof gtag === 'function') {
      gtag('event', 'lead_form_opened', {
        'total_cost': total,
        'project_sqft': getSqft(),
        'quality_tier': quality,
        'market': els.market.value
      });
    }
  }

  function closeLeadModal() {
    const modal = document.getElementById('leadModal');
    modal.style.display = 'none';
  }

  const btnGetEstimate = document.getElementById('btn-get-estimate');
  if (btnGetEstimate) {
    btnGetEstimate.addEventListener('click', () => {
      openLeadModal();
    });
  }

  const leadForm = document.getElementById('leadForm');
  if (leadForm) {
    leadForm.addEventListener('submit', async (e) => {
      e.preventDefault();
      
      const name = document.getElementById('leadName').value;
      const email = document.getElementById('leadEmail').value;
      const company = document.getElementById('leadCompany').value;
      const deliveryMethod = document.querySelector('input[name="deliveryMethod"]:checked').value;
      
      if (typeof gtag === 'function') {
        gtag('event', 'lead_submitted', {
          'name': name,
          'email': email,
          'company': company,
          'delivery_method': deliveryMethod,
          'total_cost': els.total.textContent,
          'project_sqft': getSqft(),
          'quality_tier': getQuality(),
          'market': els.market.value
        });
      }
      
      try {
        const response = await fetch('/.netlify/functions/capture-lead', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            name: name,
            email: email,
            company: company,
            deliveryMethod: deliveryMethod,
            estimate: {
              market: els.market.value,
              sqft: getSqft(),
              quality: getQuality(),
              total: els.total.textContent,
              options: {
                furniture: els.opt.furniture?.checked,
                ffe: els.opt.ffe?.checked,
                art: els.opt.art?.checked,
                smart: els.opt.smart?.checked,
                green: els.opt.green?.checked,
                fast: els.opt.fast?.checked,
                fullhvac: els.opt.fullhvac?.checked
              }
            }
          })
        });
        
        if (response.ok) {
          if (deliveryMethod === 'pdf') {
            showCustomAlert('Thank you ' + name + '! Your PDF is downloading now.');
            await downloadPDF();
          } else if (deliveryMethod === 'whatsapp') {
            showCustomAlert('Thank you ' + name + '! Opening WhatsApp...');
            whatsappEstimate();
          } else {
            showCustomAlert('Thank you ' + name + '! Your estimate has been sent to ' + email);
          }
          
          closeLeadModal();
          document.getElementById('leadForm').reset();
        } else {
          showCustomAlert('Error processing your request. Please try again.');
        }
      } catch (error) {
        console.error('Lead capture error:', error);
        showCustomAlert('Error processing your request. Please try again.');
      }
    });
  }

  const leadModal = document.getElementById('leadModal');
  if (leadModal) {
    leadModal.addEventListener('click', (e) => {
      if (e.target.id === 'leadModal') {
        closeLeadModal();
      }
    });
  }

  els.btnConsult.addEventListener('click', () => {
    if (typeof gtag === 'function') {
      gtag('event', 'consultation_requested', {
        'total_cost': els.total.textContent,
        'project_sqft': getSqft(),
        'quality_tier': getQuality()
      });
    }
  });

  function setLang(lang) {
    if (lang !== 'en' && lang !== 'ar') return;
    state.lang = lang;
    localStorage.setItem('trdb-lang', lang);
    els.langEN.classList.toggle('active', lang === 'en');
    els.langAR.classList.toggle('active', lang === 'ar');
    applyI18n();
    update();
  }
  
  els.langEN.addEventListener('click', () => setLang('en'));
  els.langAR.addEventListener('click', () => setLang('ar'));

  /* ---------------- INIT ---------------- */
  function init() {
    els.langEN.classList.toggle('active', state.lang === 'en');
    els.langAR.classList.toggle('active', state.lang === 'ar');

    ensureUnitToggle();
    updateUnitToggleUI();

    applyI18n();
    setFill();
    reflectDisplaySize();
    update();

    const initVal = parseInt(els.sqft.value, 10) || 0;
    markActiveChips(initVal);
  }
  init();
})();
// === START: LOCATION DRILL-DOWN SYSTEM (ZONE + BUILDING) ===
const locationData = {
  uae: {
    dubai: {
      zones: ["DIFC", "JLT", "Business Bay", "Downtown Dubai", "Dubai Media City"],
      buildings: {
        "DIFC": ["ICD Brookfield Place", "Emirates Financial Towers", "Index Tower", "Gate Avenue"],
        "JLT": ["Silver Tower (AG Tower)", "Indigo Tower", "Saba Tower"],
        "Business Bay": ["Vision Tower", "Executive Towers", "Iris Bay Tower"],
        "Downtown Dubai": ["Emirates Office Tower", "The Address Boulevard"],
        "Dubai Media City": ["Shatha Tower", "Business Central Towers", "The LOFT Offices"]
      }
    },
    abudhabi: {
      zones: ["Al Maryah Island", "Reem Island", "Khalidiya"],
      buildings: {
        "Al Maryah Island": ["Al Maryah Tower", "Al Maqam Tower"],
        "Reem Island": ["Tamouh Tower", "Addax Tower"],
        "Khalidiya": ["Khalidiya Towers", "CI Tower"]
      }
    }
  }
};

function onMarketChange() {
  const market = document.getElementById('marketSelect').value;
  const refineSection = document.getElementById('refine-location');
  const zoneSelect = document.getElementById('zone');
  const buildingSelect = document.getElementById('building');

  zoneSelect.innerHTML = '<option>Select zone</option>';
  zoneSelect.disabled = true;
  buildingSelect.innerHTML = '<option>Select building</option>';
  buildingSelect.disabled = true;
  refineSection.style.display = 'none';

  if (!market) return;

  let city = '';
  if (market === 'uae-dubai') city = 'dubai';
  else if (market === 'uae-abudhabi') city = 'abudhabi';
  else return;

  refineSection.style.display = 'block';

  const zones = locationData.uae[city]?.zones || [];
  zones.forEach(z => {
    zoneSelect.innerHTML += `<option value="${z}">${z}</option>`;
  });
  zoneSelect.disabled = false;

  recalc();
}

function loadBuildings() {
  const zone = document.getElementById('zone').value;
  const buildingSelect = document.getElementById('building');
  const market = document.getElementById('marketSelect').value;

  buildingSelect.innerHTML = '<option>Select building</option>';
  buildingSelect.disabled = true;

  let city = '';
  if (market === 'uae-dubai') city = 'dubai';
  else if (market === 'uae-abudhabi') city = 'abudhabi';
  else return;

  const buildings = locationData.uae[city]?.buildings[zone] || [];
  buildings.forEach(b => {
    buildingSelect.innerHTML += `<option value="${b}">${b}</option>`;
  });
  buildingSelect.disabled = false;

  recalc();
}
// === END: LOCATION DRILL-DOWN SYSTEM ===
